node_version: v6.10.0
yarn_version: 0.21.3
serverless_version: 1.9.0
dynamodb_download_url: http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz
dynamodb_filename: dynamodb_local_latest.tar.gz
